package telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import telas.Estoque;


public class InfoOngs extends javax.swing.JFrame {

    /**
     * Creates new form InfoOngs
     */
    public InfoOngs() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Icone i = new Icone();
        i.InserirIcone(this);
    }
    DestacaLinha dstqLinha = new DestacaLinha();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaOngs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info ONG's"));

        tabelaOngs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ONG Banco de Alimentos", "02.736.449/0003-00", "(11)95029-0006", "R. Atibaia", "218", "Perdizes", "São Paulo", "SP", "info@bancodealimentos.org.br"},
                {"Anjos da noite", "67.637.231/0001-81", "(11)98160-8407", "R. desembargador Rocha Portela", "634", "Artur Alvim", "São Paulo", "SP", "anjos@anjosdanoite.org.br"},
                {"Gastromotiva", "08.505.223/0001-12", "(11)96013-3031", "Rua Marselha", "728", "Jaguaré", "São Paulo", "SP", "gastromotiva@gastromotiva.org"},
                {"Instituto Alimentar", "28.247.668/0001-57", "(11)4119-2195", "R. Nossa Sra. de Montevergine", "48", "Vila Santana", "São Paulo", "SP", "contato@institutoaliemntar.org.br"},
                {"Alimento para todos", "41.683.874/0001-78", "(19) 99320-3000", "R. conselheiro Antonio Carlos", "1785", "Jd. Campos Eliseos", "Campinas", "SP", "grupoalimentosparatodos@gmail.com"}
            },
            new String [] {
                "Nome", "CNPJ", "Telefone", "Logradouro", "N°", "Bairro", "Cidade", "Estado", "E-mail"
            }
        ));
        tabelaOngs.setColumnSelectionAllowed(true);
        tabelaOngs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaOngsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaOngs);
        tabelaOngs.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMenu1.setText("Inicio");

        jMenuItem1.setText("Pagina Inicial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("...");

        jMenuItem2.setText("Sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaOngsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaOngsMouseClicked
        
        int index = tabelaOngs.getSelectedRow();
        
        
        TableModel model = tabelaOngs.getModel();
        
        String Nome = model.getValueAt(index, 0).toString();
        String CNPJ = model.getValueAt(index, 1).toString();
        String Telefone = model.getValueAt(index, 2).toString();
        String Logradouro = model.getValueAt(index, 3).toString();
        String N = model.getValueAt(index, 4).toString();
        String Bairro = model.getValueAt(index, 5).toString();
        String Cidade = model.getValueAt(index, 6).toString();
        String Estado = model.getValueAt(index, 7).toString();
        String Email = model.getValueAt(index, 8).toString();
        
        dstqLinha.setVisible(true);
        dstqLinha.pack();
        dstqLinha.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        dstqLinha.campoNome.setText(Nome);
        dstqLinha.campoCNPJ.setText(CNPJ);
        dstqLinha.campoTelefone.setText(Telefone);
        dstqLinha.campoLogradouro.setText(Logradouro);
        dstqLinha.campoN.setText(N);
        dstqLinha.campoBairro.setText(Bairro);
        dstqLinha.campoCidade.setText(Cidade);
        dstqLinha.campoEstado.setText(Estado);
        dstqLinha.campoEmail.setText(Email);
        
    }//GEN-LAST:event_tabelaOngsMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           // TODO add your handling code here:
           this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente finalizar o programa?","Atenção",
                JOptionPane.YES_OPTION);
                
        if (opcao == JOptionPane.YES_OPTION){
            System.exit(0);
        }
     }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static void addColNaTabela(Object[] dados){
        DefaultTableModel model = (DefaultTableModel)tabelaOngs.getModel();
        model.addRow(dados);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoOngs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoOngs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoOngs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoOngs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoOngs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tabelaOngs;
    // End of variables declaration//GEN-END:variables
}
